# Generated by Django 4.2.16 on 2024-11-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_notas', '0002_remove_notafinal_registrado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=300),
        ),
    ]
