# Generated by Django 5.1.3 on 2024-11-23 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_notas', '0004_notafinal_modified_at_notafinal_modified_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFinalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('nota_anterior', models.FloatField()),
                ('nota_atual', models.FloatField()),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('nota_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_notas.notafinal')),
            ],
        ),
    ]
