# Generated by Django 5.1.3 on 2024-11-23 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_notas', '0005_notafinalaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notafinalaudit',
            options={'verbose_name': 'Nota Final Audit', 'verbose_name_plural': 'Notas Finais Audits'},
        ),
        migrations.RenameField(
            model_name='notafinalaudit',
            old_name='modified_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='notafinalaudit',
            name='is_first_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notafinalaudit',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notafinalaudit',
            name='nota_anterior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notafinalaudit',
            name='nota_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='sistema_notas.notafinal'),
        ),
    ]
