# Generated by Django 5.1.3 on 2024-11-23 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_notas', '0006_alter_notafinalaudit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notafinalaudit',
            options={'verbose_name': 'Histórico de Nota Final', 'verbose_name_plural': 'Históricos de Notas Finais'},
        ),
        migrations.AlterField(
            model_name='notafinalaudit',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notafinalaudit',
            name='nota_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='sistema_notas.notafinal'),
        ),
    ]
