# Generated by Django 5.1.3 on 2024-11-23 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_notas', '0007_alter_notafinalaudit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notafinalaudit',
            options={},
        ),
        migrations.RemoveField(
            model_name='notafinalaudit',
            name='is_first_entry',
        ),
        migrations.AddField(
            model_name='notafinalaudit',
            name='status',
            field=models.CharField(default='Sem status', max_length=20, verbose_name='Status Atual'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notafinalaudit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Modificação'),
        ),
        migrations.AlterField(
            model_name='notafinalaudit',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='notafinalaudit',
            name='nota_anterior',
            field=models.FloatField(blank=True, null=True, verbose_name='Nota Anterior'),
        ),
        migrations.AlterField(
            model_name='notafinalaudit',
            name='nota_atual',
            field=models.FloatField(verbose_name='Nota Atual'),
        ),
        migrations.AlterField(
            model_name='notafinalaudit',
            name='nota_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='sistema_notas.notafinal', verbose_name='Nota Final'),
        ),
    ]
