# Generated by Django 5.1.3 on 2024-11-24 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_notas', '0008_alter_notafinalaudit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='usuarios_permitidos',
            field=models.ManyToManyField(blank=True, related_name='turmas_permitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notafinalaudit',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notafinal_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
