# Generated by Django 5.1.3 on 2024-11-24 22:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_notas', '0009_turma_usuarios_permitidos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='usuarios_permitidos',
            field=models.ManyToManyField(blank=True, related_name='disciplinas_permitidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Permitidos'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='turma',
            name='usuarios_permitidos',
            field=models.ManyToManyField(blank=True, related_name='turmas_permitidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Permitidos'),
        ),
    ]
