# Generated by Django 5.1.3 on 2024-11-26 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_notas', '0010_disciplina_usuarios_permitidos_alter_disciplina_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='usuarios_permitidos',
            field=models.ManyToManyField(blank=True, related_name='disciplinas_permitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DisciplinaTurma',
        ),
    ]
